version: '3'
services:
  mosquitto:
    container_name: mosquitto
    restart: always
    build:
      context: ./mosquitto
      dockerfile: Dockerfile
    ports:
      - "1883:1883"
    networks:
      - reseau
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - ./mosquitto/data:/mosquitto/data
      - ./mosquitto/logs:/mosquitto/logs

networks:
  reseau: